// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Cor1440Gen__AcfechapfController from "./cor1440_gen/acfechapf_controller"
application.register("cor1440-gen--acfechapf", Cor1440Gen__AcfechapfController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Msip__BitacoraapController from "./msip/bitacoraap_controller"
application.register("msip--bitacoraap", Msip__BitacoraapController)

import Msip__CancelarVacioEsEliminarController from "./msip/cancelar_vacio_es_eliminar_controller"
application.register("msip--cancelar-vacio-es-eliminar", Msip__CancelarVacioEsEliminarController)

import Msip__EnviarautomaticoController from "./msip/enviarautomatico_controller"
application.register("msip--enviarautomatico", Msip__EnviarautomaticoController)

import Msip__FiltroTanController from "./msip/filtro_tan_controller"
application.register("msip--filtro-tan", Msip__FiltroTanController)

import Msip__GeodepController from "./msip/geodep_controller"
application.register("msip--geodep", Msip__GeodepController)

import Msip__SindocautController from "./msip/sindocaut_controller"
application.register("msip--sindocaut", Msip__SindocautController)
